
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:8084
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer